# Generated by Django 2.2.20 on 2021-09-23 08:43

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_flat_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='owners_pure_phonenumber',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20, region=None, verbose_name='Нормализованный номер владельца'),
        ),
    ]
