# Generated by Django 2.2.20 on 2021-09-23 08:46

from django.db import migrations
import phonenumbers


def fill_owners_pure_phonenumber_field(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        flat.owners_pure_phonenumber = phonenumbers.parse(flat.owners_phonenumber, 'RU')
        flat.save()


def roll_back(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        flat.owners_pure_phonenumber = ''
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_flat_owners_pure_phonenumber'),
    ]

    operations = [
        migrations.RunPython(fill_owners_pure_phonenumber_field, roll_back)
    ]
