# Generated by Django 2.2.20 on 2021-09-26 18:23

from django.db import migrations


def move_owners_to_separate_model(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.all():
        owner, created = Owner.objects.get_or_create(
            full_name=flat.owner,
            phonenumber=flat.owners_phonenumber,
            defaults={'pure_phonenumber': flat.owners_pure_phonenumber},
        )
        owner.flats.add(flat)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_owner'),
    ]

    operations = [
        migrations.RunPython(move_owners_to_separate_model)
    ]
