# Generated by Django 2.2.20 on 2021-09-26 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_move_owners_to_separate_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='owners_phonenumber',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='owners_pure_phonenumber',
        ),
    ]
